/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-03-23 07:29:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<htmL>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"home.css\" />\r\n");
      out.write("        <title>Virtual Vista</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"></script>  \r\n");
      out.write("        <style>\r\n");
      out.write("            body\r\n");
      out.write("            {\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("            .column1 {\r\n");
      out.write("                float: left;\r\n");
      out.write("                 padding: 80px;\r\n");
      out.write("}\r\n");
      out.write(".column1 {\r\n");
      out.write("  flex: 33.33%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("           .column {\r\n");
      out.write("                float: left;\r\n");
      out.write("                margin-top: 10px;\r\n");
      out.write("                margin-left:50px;\r\n");
      out.write("                 padding: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .row::after {\r\n");
      out.write("             content: \"\";\r\n");
      out.write("                clear: both;\r\n");
      out.write("             display: table;\r\n");
      out.write("            }\r\n");
      out.write("            .row {\r\n");
      out.write("  display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column {\r\n");
      out.write("  flex: 33.33%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-info-subtle text-emphasis-danger\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.somo.nl%2Fwp-content%2Fuploads%2F2012%2F12%2Fhuman-rights-programme-bolsters-grievance-mechanisms-1.jpg&imgrefurl=https%3A%2F%2Fwww.somo.nl%2Fhuman-rights-programme-bolsters-grievance-mechanisms%2F&tbnid=1ox2fegoswr60M&vet=12ahUKEwip97uL8Yf9AhVegtgFHelmD0kQMygMegUIARDXAQ..i&docid=noSUwSjLWVN63M&w=1307&h=1294&q=grievance%20logo&ved=2ahUKEwip97uL8Yf9AhVegtgFHelmD0kQMygMegUIARDXAQ\" /></a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"eventreg.jsp\">Event Registration</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"particreg.jsp\">Participant Registration</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        Events\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"culturalevent.jsp\">Cultural Events</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"technicalevent.jsp\">Technical Events</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"sportsevent.jsp\">Sport Events</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"about.jsp\">About</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"feedback.jsp\">Feedback</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("                    <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("                    <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"column\">\r\n");
      out.write("              <img src=\"image1.jpg\" alt=\"Snow\" style=\"width:90%\"><br><br>\r\n");
      out.write("              <p><i> the Lorem ipsum dolor Lorem, Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia consequatur perferendis assumenda beatae quod iste commodi fuga at, dolores maxime adipisci dolorum qui sapiente rem inventore obcaecati accusantium velit dicta deleniti alias doloribus. Dolore, iste. Temporibus eius nulla beatae est facere accusantium, a voluptates commodi, repudiandae molestiae nisi, id deserunt neque doloremque nobis eum odit eveniet excepturi illo perferendis molestias eaque ratione? Porro, omnis consequuntur vitae rem nobis amet accusamus nesciunt eos ut officiis. Optio inventore necessitatibus cumque assumenda atque officiis dolore ea tempore molestiae in, minima deserunt unde error ex illo officia ad laboriosam voluptatibus, aut ipsam tenetur. Quia. ipsum dolor sit amet consectetur adipisicing elit. Voluptas quos, omnis magni architecto porro praesentium qui. Tenetur possimus natus at, ducimus voluptates amet accusantium dolores? Animi, soluta deleniti! Magni nesciunt expedita vitae distinctio harum laudantium deleniti adipisci. Laborum commodi consequatur vel, quaerat, quo recusandae laudantium facere odit quam at magni eaque. Quisquam vero mollitia accusamus vitae rerum sit optio veniam id enim illum impedit quasi corrupti corporis facilis et quo fugiat aut, sapiente rem aliquid. Laudantium eveniet repellat, maiores reiciendis, ea inventore veniam officiis veritatis eaque tempore, maxime reprehenderit ullam natus ratione laborum esse adipisci consequuntur suscipit consequatur ipsam rerum?sit amet, consectetur adipisicing elit. Debitis nobis quos eveniet! Perspiciatis eum rem, placeat quod optio necessitatibus quas vero architecto est fugit natus soluta voluptates consectetur atque inventore!</i></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"column1\">\r\n");
      out.write("               <p> <i>The Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero fuga aspernatur a recusandae quibusdam vel laborum cumque temporibus eos. Excepturi neque eius temporibus quis quam rem at architecto voluptatem sequi accusantium natus, dolorem deserunt? Quae id non eveniet est modi labore incidunt harum praesentium deserunt. Placeat corporis facere mollitia quidem et saepe hic qui nemo ipsa non in voluptatem molestias possimus ab, incidunt perspiciatis, ad totam sapiente neque obcaecati quasi praesentium perferendis. Veniam eum excepturi aliquam adipisci sunt. Ipsa atque nesciunt, exercitationem unde, tempore fuga tenetur, molestiae ratione nam ea sapiente. Similique quos accusamus aspernatur magni, in debitis sed possimus pariatur adipisci, commodi voluptates assumenda nulla nostrum illo! Deleniti consequatur est reiciendis autem error ex. Ad error consequuntur officiis minima molestiae perferendis hic modi praesentium, ut quis dolorum, eaque possimus aperiam harum explicabo aliquid consectetur veniam. Omnis facere corrupti quaerat, nulla soluta numquam doloribus fugiat earum. Magni veritatis incidunt ad commodi a beatae minima perferendis expedita minus debitis vel, voluptatem est atque! Voluptatem quis odit fugiat consequuntur dolore inventore placeat molestiae ipsum facere praesentium quia alias, quod dolor reprehenderit? Nemo iusto commodi cumque tempora? Alias, libero porro. Veniam sunt libero molestias vel ab minus, ipsam quod accusamus quia assumenda possimus.</i></p>\r\n");
      out.write("              <img src=\"image2.jpg\" alt=\"Mountains\" style=\"width:90%\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Carousel -->\r\n");
      out.write("        <div id=\"carouselExampleControls\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("              <div class=\"carousel-item active\">\r\n");
      out.write("                <img class=\"d-block w-100\" src=\"...\" alt=\"First slide\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-item\">\r\n");
      out.write("                <img class=\"d-block w-100\" src=\"...\" alt=\"Second slide\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-item\">\r\n");
      out.write("                <img class=\"d-block w-100\" src=\"...\" alt=\"Third slide\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"carousel-control-prev\" href=\"#carouselExampleControls\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("              <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"sr-only\">Previous</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"carousel-control-next\" href=\"#carouselExampleControls\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("              <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"sr-only\">Next</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("    </body>\r\n");
      out.write("</htmL>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
